# Generated by Django 4.1.5 on 2023-01-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_billingaddress_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('F', 'Facturacion'), ('E', 'Envio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('V', 'venta'), ('N', 'nuevo'), ('P', 'promocion')], max_length=1),
        ),
    ]
